USE project26; 

SHOW TABLES; 

SELECT * FROM mobilesales; 

DESCRIBE mobilesales;

SELECT City, COUNT(City) AS Total_city
FROM mobilesales
GROUP BY City
ORDER BY Total_city ASC;  

-- 1. Total revenue generated by each mobile brand
SELECT Brand, ROUND(SUM(`Price Per Unit`),2) AS Total_revenue  
FROM MobileSales
GROUP BY Brand
ORDER BY Total_revenue DESC;

-- 2. Top 5 cities by total sales revenue.
SELECT City, round(SUM(`Price Per Unit`),2) AS Total_sales 
FROM Mobilesales
GROUP BY City 
ORDER BY Total_sales DESC
LIMIT 5; 

-- 3. Determine the total number of transactions for each payment method.
SELECT `Payment Method`, COUNT(`Payment Method`) as Total_transaction
FROM mobilesales
GROUP BY `Payment Method` 
ORDER BY Total_transaction DESC;

-- 4. Calculate the average customer rating for each brand.
SELECT Brand, ROUND(AVG(`Customer Ratings`),1) AS Avg_rating 
FROM mobilesales
GROUP BY Brand
ORDER BY Avg_rating DESC;

-- 5. Find the top 10 best-selling mobile models by units sold.
SELECT `Mobile Model`, `Units Sold` 
FROM mobilesales
ORDER BY `Units Sold` DESC
LIMIT 10;

SELECT DAYNAME(
       STR_TO_DATE(Date, "%d%m%y")) AS WeekDay
FROM Mobilesales; 

SELECT * FROM Mobilesales;

DESC mobilesales;   # Show the data types of each columns

-- Update table
ALTER TABLE mobilesales
ADD COLUMN New_Date Date;

SET SQL_SAFE_UPDATES = 0;

UPDATE mobilesales
SET New_Date = STR_TO_DATE(Date, '%d/%m/%Y');

ALTER TABLE mobilesales    -- Deleted old date column
DROP COLUMN Date; 

-- 6. Identify the day of the week with the highest sales volume.
SELECT DAYNAME(
		STR_TO_DATE(Date, "%d/%m/%Y")) AS WeekDay,
		ROUND(SUM(`Units Sold` * `Price Per Unit`),2) AS Highest_sales 
FROM Mobilesales
GROUP BY WeekDay
ORDER BY Highest_sales DESC
LIMIT 1; 

-- 7. Calculate the total units sold in each city. 
SELECT City, COUNT(`Units Sold`) AS Total_units_sold 
FROM mobilesales
GROUP BY City
ORDER BY Total_units_sold DESC;  

-- 8. Find the average selling price for each brand.
SELECT Brand, ROUND(AVG(`Price Per Unit`),2) AS Avg_selling_price
FROM mobilesales
GROUP BY Brand
ORDER BY Avg_selling_price DESC; 

-- 9. Determine how many purchases were made by customers under the age of 30.
SELECT COUNT(*) AS Total_purchase
FROM mobilesales
WHERE `Customer Age` < 30; 

SELECT * FROM mobilesales;

-- 10. Calculate the percentage contribution of each brand to total revenue.
SELECT Brand,
       ROUND(
       SUM(`Units Sold` * `Price Per Unit`) * 100/ 
       SUM(SUM(`Units Sold` * `Price Per Unit`)) OVER(),
       2) AS Revenue_percent
FROM mobilesales
GROUP BY Brand 
ORDER BY Revenue_percent DESC; 

SELECT * FROM Mobilesales;

############## Advanced SQL Analysis ################

-- 11. Find the highest revenue-generating mobile model in each city.
SELECT City, `Mobile Model`, MAX(`Units Sold` * `Price Per Unit`) AS Highest_revenue 
FROM mobilesales 
GROUP BY City                                                       # Wrong code
ORDER BY Highest_revenue DESC; 

-- 11. Find the highest revenue-generating mobile model in each city.

SELECT City,
        `Mobile Model`,
        (`Units Sold` * `Price Per Unit`) AS Revenue,
ROW_NUMBER() OVER(PARTITION BY City ORDER BY (`Units Sold` * `Price Per Unit`) DESC) AS Row_num
FROM mobilesales;

WITH Common_table AS(
	 SELECT City,
        `Mobile Model`,
        (`Units Sold` * `Price Per Unit`) AS Revenue,
ROW_NUMBER() OVER(PARTITION BY City ORDER BY (`Units Sold` * `Price Per Unit`) DESC) AS Row_num
FROM mobilesales
)
SELECT City,
	  `Mobile Model`,
      ROUND(Revenue) AS Highest_revenue
FROM Common_table
WHERE Row_num = 1;    

-- Create new column of Total Revenue

ALTER TABLE mobilesales
ADD COLUMN Total_Revenue INT;

UPDATE mobilesales
SET Total_Revenue = (`Units Sold` * `Price Per Unit`);

SELECT * FROM mobilesales;

-- 12. Identify the top 3 brands in each city based on revenue.
WITH Common_Table AS(
SELECT City, Brand, 
       SUM(Total_Revenue) As Revenue,
ROW_NUMBER() OVER(PARTITION BY City 
			 ORDER BY SUM(Total_Revenue) DESC
             ) AS Row_num 
FROM mobilesales  
GROUP BY City, Brand
)    
SELECT *
FROM Common_Table   
WHERE Row_num <=3;     

-- 13. Analyze monthly sales trends for each brand.
SELECT Brand, SUM(Total_Revenue) AS Revenue, MONTHNAME(New_Date) AS Months
FROM MobileSales
GROUP BY Brand, MONTHNAME(New_Date)
ORDER BY Revenue DESC; 

-- 14. Rank brands by total revenue using window functions.
SELECT brand, SUM(Total_Revenue) AS Revenue,
ROW_NUMBER() OVER(  
              ORDER BY SUM(Total_Revenue) DESC) AS Rank_num
FROM mobilesales
GROUP BY brand;

-- 15. Identify customers who made more than 3 purchases.
SELECT `Customer Name`, COUNT(*) AS Total_Purchase 
FROM mobilesales
GROUP BY `Customer Name`
HAVING COUNT(*) > 3
ORDER BY Total_Purchase;

-- 16. Find customers whose total spending is above the average customer spending.

SELECT `Customer Name`,
       SUM(Total_Revenue) AS Total_Spending
FROM mobilesales
GROUP BY `Customer Name`      
HAVING SUM(Total_Revenue) >       
(
    SELECT AVG(Customer_Spending) 
    FROM
    (
        SELECT SUM(Total_Revenue) AS Customer_Spending
        FROM mobilesales
        GROUP BY `Customer Name`
    ) AS Avg_Spending
);
-- 17. Calculate the running total of revenue by date.

WITH Revenue_CTC AS(
SELECT New_Date, SUM(Total_Revenue) AS Revenue
FROM mobilesales
GROUP BY New_Date
ORDER BY Revenue DESC
)
SELECT New_Date, Revenue,
       SUM(Revenue) OVER(
           ORDER BY New_Date
		) AS Total_Running
FROM Revenue_CTC; 
       
-- 18. Compare each transaction's revenue with the previous transaction using LAG().
 SELECT New_Date,
        `Customer Name`,
        Total_Revenue,
        LAG(Total_Revenue) OVER(ORDER BY New_Date) AS Previous_Revenue,
        Total_Revenue -
        LAG(Total_Revenue) OVER(ORDER BY New_Date) AS Diffrence_Revenue
FROM mobilesales;  
 
-- 19. Calculate each brand's revenue share within its city.
WITH BrandRevenue AS
(
SELECT City, Brand, SUM(Total_Revenue) AS Revenue
from mobilesales
GROUP BY City, Brand
)
SELECT City, Brand, Revenue,
       ROUND(Revenue * 100/  
             SUM(Revenue) OVER (PARTITION BY City),
		2) AS Revenue_percent
FROM BrandRevenue;

       SELECT * FROM mobilesales;      
-- 20. Identify the most preferred payment method in each city.

SELECT City, `Payment Method`, COUNT(`Payment Method`) AS Prefer_pay_mode
FROM mobilesales
GROUP BY City,`Payment Method`
ORDER BY Prefer_pay_mode DESC;

WITH Payment_Count AS(
SELECT City, `Payment Method`,
              COUNT(*) AS Total_Uses,
	ROW_NUMBER() OVER(
                 PARTITION BY City ORDER BY COUNT(*) DESC
                 ) AS Row_num
FROM mobilesales
GROUP BY City, `Payment Method`
ORDER BY Total_uses DESC
)
SELECT City, `Payment Method`, 
              Total_uses
FROM Payment_Count
WHERE Row_num = 1; 

############## Business & Industry-Level Case Studies Problems ###############

-- 21. Which brand has the highest customer satisfaction while maintaining strong sales performance?
SELECT Brand, 
ROUND(AVG(`Customer Ratings`),2) AS Avg_Rating,
SUM(`Total_Revenue`) AS Total_Sales
FROM mobilesales
GROUP BY Brand
ORDER BY Avg_Rating DESC, Total_Sales DESC;

-- 22. Which city generates the highest revenue per customer?
SELECT City, `Customer Name`, MAX(`Total_Revenue`) AS Highest_reveneu
FROM mobilesales                                                          -- wrong
GROUP BY City, `Customer Name`;


SELECT City, `Customer Name`, 
MAX(`Total_Revenue`) AS Highest_reveneu,

ROW_NUMBER() OVER(PARTITION BY City ORDER BY MAX(`Total_Revenue`)
) AS Row_num                                            -- wrong
FROM mobilesales
GROUP BY City, `Customer Name`;

-- 22. Which city generates the highest revenue per customer?  
SELECT City,
       SUM(Total_Revenue) AS Total_Revenue,
       COUNT(DISTINCT `Customer Name`) AS Total_Customers,
       SUM(Total_Revenue) /
       COUNT(DISTINCT `Customer Name`) AS Revenue_Per_Customer
FROM mobilesales
GROUP BY City
ORDER BY Revenue_Per_Customer DESC; 

-- 23. Identify mobile models overall average despite high sales.
SELECT `Mobile Model`, 
AVG(`Customer Ratings`) AS Avg_rating,
SUM(`Total_Revenue`) AS High_Sales
FROM mobilesales
GROUP BY `Mobile Model`
ORDER BY High_Sales DESC; 

-- 23. Identify low-rated mobile models (rating < overall average) despite high sales.
SELECT `Mobile Model`, 
AVG(`Customer Ratings`) AS Avg_rating,
SUM(`Total_Revenue`) AS High_Sales
FROM mobilesales
GROUP BY `Mobile Model`
HAVING AVG(`Customer Ratings`) < (SELECT AVG(`Customer Ratings`)
FROM mobilesales
)
ORDER BY High_Sales DESC;

SELECT * FROM mobilesales;

-- 24. Find repeat customers and their lifetime value (LTV)
SELECT `Customer Name`,
        COUNT(*) AS Total_Purchase,
        SUM(Total_Revenue) AS Lifetime_Value
FROM mobilesales
GROUP BY `Customer Name`
HAVING COUNT(*) > 1
ORDER BY Lifetime_Value DESC; 

-- 25. Which payment method generates the highest average order value?
SELECT `Payment Method`,
        AVG(Total_Revenue) AS High_avg_order 
FROM mobilesales
GROUP BY `Payment Method`
ORDER BY High_avg_order DESC
LIMIT 1;

-- 26. Detect seasonal trends by comparing weekday sales vs weekend sales.
SELECT
	CASE 
		WHEN DAYOFWEEK(New_Date) IN (1,7)
        THEN 'Weekend'
        ELSE 'Weekday'
	END AS Day_Type,
    COUNT(*) AS Total_orders,
    SUM(Total_Revenue) AS Total_sales,
    AVG(Total_Revenue) AS Avg_order_value   
FROM mobilesales
GROUP BY Day_Type;

-- 27. Find the top-selling model within each brand using window functions.
WITH Common_table AS (
    SELECT Brand, `Mobile Model`, 
    SUM(`Total_Revenue`) AS Total_sales,
ROW_NUMBER() OVER(
PARTITION BY Brand 
ORDER BY SUM(`Total_Revenue`)) AS Row_num
FROM mobilesales
GROUP BY Brand, `Mobile Model`
)
SELECT Brand, `Mobile Model`,
       Total_sales
FROM Common_table
WHERE Row_num = 1; 


-- 28. Segment customers into Age Groups (18-25, 26-35, 36-45, 46+) and analyze spending behavior.
SELECT 
	CASE
		WHEN `Customer Age` BETWEEN 18 AND 25 THEN '18-25'
        WHEN `Customer Age` BETWEEN 26 AND 35 THEN '26-35'
        WHEN `Customer Age` BETWEEN 36 AND 45 THEN '36-45'
        ELSE '36+' 
	END AS Age_Group,
    COUNT(DISTINCT `Customer Name`) AS Total_Customers,
    SUM(Total_Revenue) AS Total_Spending,
    ROUND(AVG(Total_Revenue),2) AS Avg_Spending
FROM mobilesales
GROUP BY Age_Group
ORDER BY Age_Group;

-- 29. Which brand depends most heavily on a single city for its revenue?

SELECT Brand, City, 
SUM(Total_Revenue) AS heavy_revenue
FROM mobilesales
GROUP BY Brand, City;

-- 30. Create a sales leaderboard showing Rank, Brand, Revenue, Units Sold, and Avg Rating. 
WITH BrandPerformance AS (
    SELECT
        Brand,
        SUM(Total_Revenue) AS Revenue,
        SUM(`Units Sold`) AS Units_Sold,
        ROUND(AVG(`Customer Ratings`), 2) AS Avg_Rating
    FROM mobilesales
    GROUP BY Brand
)
SELECT
    RANK() OVER(ORDER BY Revenue DESC) AS Brand_Rank,
    Brand,
    Revenue,        
    Units_Sold,        
    Avg_Rating       
FROM BrandPerformance;    








